/**
 * Program IDLs for the Bundie Solana programs.
 *
 * - Prediction Market: auto-generated by `anchor build` from the Rust sources.
 *   Re-copy from `packages/programs/target/idl/prediction_market.json` whenever
 *   the instruction surface changes.
 * - Strategy Token: hand-authored — the program is pinocchio, not Anchor, so
 *   there is no anchor-generated IDL. The hand-authored IDL mirrors the byte
 *   offsets declared in `programs/strategy-token/src/state/{strategy,nav_oracle,position_snapshots}.rs`
 *   and the instruction dispatcher in `lib.rs`.
 */

import predictionMarketIdl from './prediction_market.json' with { type: 'json' };
import type { PredictionMarket } from './prediction_market.js';
import strategyTokenIdl from './strategy_token.json' with { type: 'json' };
import type { StrategyToken } from './strategy_token.js';

export { predictionMarketIdl, strategyTokenIdl };
export type { PredictionMarket, StrategyToken };
export type PredictionMarketIdlType = typeof predictionMarketIdl;
export type StrategyTokenIdlType = typeof strategyTokenIdl;

/**
 * Strategy Token — pinocchio, dispatched by single-byte discriminator.
 *
 *   0 → create_strategy
 *   1 → buy_shares      (USDC deposit into strategy, mints shares)
 *   2 → redeem_shares   (burn shares, receive USDC)
 *   3 → update_nav      (cranker-permissionless NAV refresh)
 *   4 → rebalance       (creator rebalances portfolio)
 *   5 → snapshot_positions  (keeper, 24h-rate-limited composition snapshot)
 *
 * Account discriminators (8 bytes, at offset 0 of each account):
 *   Strategy          : [0xd0, 0x82, 0x35, 0xce, 0x9a, 0x7f, 0x5b, 0x11]
 *   NavOracle         : [0xa1, 0x4e, 0x73, 0x20, 0xbc, 0x44, 0x61, 0x05]
 *   PositionSnapshots : [0x7d, 0xa9, 0x1f, 0x4c, 0x62, 0x30, 0x8b, 0xe1]
 *
 * Decoding is handled by the hand-rolled Borsh readers in @bundie/sol-cli
 * (`src/accounts.ts`) and the webapp (`lib/chain.ts`).
 */
export const STRATEGY_TOKEN_INSTRUCTIONS = {
  CREATE_STRATEGY:    0,
  BUY_SHARES:         1,
  REDEEM_SHARES:      2,
  UPDATE_NAV:         3,
  REBALANCE:          4,
  SNAPSHOT_POSITIONS: 5,
} as const;

export const STRATEGY_ACCOUNT_DISCRIMINATOR          = new Uint8Array([0xd0, 0x82, 0x35, 0xce, 0x9a, 0x7f, 0x5b, 0x11]);
export const NAV_ORACLE_ACCOUNT_DISCRIMINATOR        = new Uint8Array([0xa1, 0x4e, 0x73, 0x20, 0xbc, 0x44, 0x61, 0x05]);
export const POSITION_SNAPSHOTS_ACCOUNT_DISCRIMINATOR = new Uint8Array([0x7d, 0xa9, 0x1f, 0x4c, 0x62, 0x30, 0x8b, 0xe1]);
