/**
 * Program IDLs for the Bundie Solana programs.
 *
 * Prediction Market is auto-generated by `anchor build` from the Rust
 * sources. Re-copy from `packages/programs/target/idl/prediction_market.json`
 * whenever the instruction surface changes.
 */

import predictionMarketIdl from './prediction_market.json' with { type: 'json' };
import type { PredictionMarket } from './prediction_market.js';

export { predictionMarketIdl };
export type { PredictionMarket };
export type PredictionMarketIdlType = typeof predictionMarketIdl;
