// IDL types will be auto-generated by Anchor after build
// For now, export placeholder types

/** Strategy Token Program IDL — auto-generated after `anchor build` */
export type StrategyTokenIDL = Record<string, unknown>

/** Prediction Market Program IDL — auto-generated after `anchor build` */
export type PredictionMarketIDL = Record<string, unknown>

// TODO: After running `anchor build`, copy generated IDL JSON files here
// and create proper TypeScript types from them
//
// import strategyTokenIdl from './strategy_token.json'
// import predictionMarketIdl from './prediction_market.json'
// export { strategyTokenIdl, predictionMarketIdl }
