/**
 * warmup.ts — deterministic first-tick for newly-active agents.
 *
 * Why: when a wizard-created agent flips to status='active' the supervisor's
 * normal LLM-driven tick adds 10–20s of brain latency before any visible
 * activity. For demo-grade UX we want a surfpool action visible within
 * a few seconds of agent activation. The warmup loop runs at 1s cadence,
 * picks an action deterministically from the agent's own program_allowlist
 * (so we honor the user's wizard selections — never hardcoded to one
 * protocol), and executes it via the same action-executor path the brain
 * would use.
 *
 * After this single fast action, the supervisor's normal LLM tick takes
 * over for all subsequent ticks — the brain still drives strategy.
 *
 * Coordination via Postgres column `agents.warmup_done_at`:
 *   - NULL means "needs warmup"
 *   - timestamp means "warmup ran (or is legacy/already-running)"
 * Backfilled to created_at for every existing agent during migration so
 * only NEW agents trigger warmups.
 */
import { Connection, Keypair } from "@solana/web3.js";
import { join } from "node:path";
import { dbQuery } from "./db.js";
import { ensureSurfpoolUsdc } from "./surfpool-seed.js";
import { executeAction, isSurfpoolReachable } from "./action-executor.js";

/**
 * Map a programId we see in `policies_yaml.program_allowlist` to the
 * BrainAction protocol enum. Mirrors LEND_PROGRAM/LST_PROGRAM in the
 * action-executor — keep in sync if a new wired protocol is added.
 */
const PROGRAM_TO_PROTOCOL: Record<
  string,
  | { kind: "lend"; protocol: "kamino" | "marginfi" | "solend" }
  | { kind: "lst"; protocol: "marinade" | "jito" }
> = {
  KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD: { kind: "lend", protocol: "kamino" },
  MFv2hWf31Z9kbCa1snEPYctwafyhdvnV7FZnsebVacA: { kind: "lend", protocol: "marginfi" },
  So1endDq2YkqhipRh3WViPa8hdiSpxWy6z3Z6tMCpAo: { kind: "lend", protocol: "solend" },
  MarBmsSgKXdrN1egZf5sqe1TMai9K1rChYNDJgjq7aD: { kind: "lst", protocol: "marinade" },
  SPoo1Ku8WFXoNDMHPsrGSTSG1Y47rzgn41SLUNakuHy: { kind: "lst", protocol: "jito" },
};

// Deterministic preference: cheapest-to-execute lending first, then LST.
// Matches the brain prompt's framing of lending as the "warmup" action.
const PREFERENCE: Array<keyof typeof PROGRAM_TO_PROTOCOL> = [
  "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD",  // Kamino
  "MFv2hWf31Z9kbCa1snEPYctwafyhdvnV7FZnsebVacA",  // MarginFi
  "So1endDq2YkqhipRh3WViPa8hdiSpxWy6z3Z6tMCpAo",  // Solend
  "MarBmsSgKXdrN1egZf5sqe1TMai9K1rChYNDJgjq7aD",  // Marinade
  "SPoo1Ku8WFXoNDMHPsrGSTSG1Y47rzgn41SLUNakuHy",  // Jito
];

interface PendingWarmup {
  sns: string;
  agentSecretKey: string;
  policiesYaml: string;
  vaultPda: string;
  seedAmountBusd: string | null;
}

/**
 * Find every active agent that hasn't been warmed up yet. Cheap query —
 * indexed on (status, warmup_done_at). Returns an empty list if the column
 * doesn't exist yet (defensive: lets old daemon images run against a new
 * DB and vice-versa during rollout).
 */
async function loadPendingWarmups(): Promise<PendingWarmup[]> {
  try {
    const r = await dbQuery<{
      sns: string;
      agent_secret_key: string | null;
      policies_yaml: string | null;
      vault_pda: string;
      seed_amount_busd: string | null;
    }>(
      `SELECT sns, agent_secret_key, policies_yaml, vault_pda, seed_amount_busd
         FROM agents
         WHERE status = 'active'
           AND warmup_done_at IS NULL
         LIMIT 10`,
    );
    if (!r) return [];
    return r.rows.flatMap((row) => {
      if (!row.agent_secret_key || !row.policies_yaml) return [];
      return [
        {
          sns: row.sns,
          agentSecretKey: row.agent_secret_key,
          policiesYaml: row.policies_yaml,
          vaultPda: row.vault_pda,
          seedAmountBusd: row.seed_amount_busd,
        },
      ];
    });
  } catch (err) {
    const msg = (err as Error).message;
    if (msg.includes("warmup_done_at")) {
      console.warn("[warmup] schema not yet migrated, skipping");
      return [];
    }
    throw err;
  }
}

/**
 * Pick a warmup action from the agent's own allowlist. We walk PREFERENCE
 * in order and use the first programId the agent has access to. Returns
 * null if the agent has no wired lending/LST protocol allowlisted (very
 * unusual — the wizard always includes at least one).
 */
function pickWarmupAction(
  policiesYaml: string,
):
  | {
      type: "lend_deposit";
      protocol: "kamino" | "marginfi" | "solend";
      args: { amountUsdcUi: number };
    }
  | {
      type: "lst_stake";
      protocol: "marinade" | "jito";
      args: { amountSolUi: number };
    }
  | null {
  // Hand-parse just the program_allowlist. We don't need a full YAML
  // dependency for this — the policy file is generated by the backend
  // and has a stable shape.
  const allowedProgramIds = new Set<string>();
  const lines = policiesYaml.split("\n");
  let inAllowlist = false;
  for (const line of lines) {
    if (line.match(/^\s*-\s*id:\s*program_allowlist/)) {
      inAllowlist = true;
      continue;
    }
    if (inAllowlist && line.match(/^\s*-\s*id:/)) {
      // hit the next policy id
      inAllowlist = false;
    }
    if (inAllowlist) {
      const m = line.match(/programId:\s*"?([A-Za-z0-9]+)"?/);
      if (m) allowedProgramIds.add(m[1]);
    }
  }

  for (const pid of PREFERENCE) {
    if (!allowedProgramIds.has(pid)) continue;
    const entry = PROGRAM_TO_PROTOCOL[pid];
    if (entry.kind === "lend") {
      return {
        type: "lend_deposit",
        protocol: entry.protocol,
        args: { amountUsdcUi: 5 },
      };
    }
    if (entry.kind === "lst") {
      return {
        type: "lst_stake",
        protocol: entry.protocol,
        args: { amountSolUi: 0.05 },
      };
    }
  }
  return null;
}

interface WarmupContext {
  surfpool: Connection;
  devnet: Connection;
}

/**
 * Run the warmup action for one agent. Catches all errors so a bad row
 * can't kill the loop. Marks warmup_done_at unconditionally on success
 * OR error so we don't retry forever — a failed warmup is fine, the
 * supervisor's normal LLM tick will pick the agent up on the next 15s
 * cycle.
 */
async function runWarmupForAgent(
  agent: PendingWarmup,
  ctx: WarmupContext,
): Promise<void> {
  console.log(`[warmup] starting ${agent.sns}`);
  const t0 = Date.now();
  let kp: Keypair;
  try {
    kp = Keypair.fromSecretKey(
      Uint8Array.from(JSON.parse(agent.agentSecretKey)),
    );
  } catch (err) {
    console.error(
      `[warmup] ${agent.sns} secret-key parse failed: ${(err as Error).message}`,
    );
    await markWarmupDone(agent.sns).catch(() => {});
    return;
  }

  // The supervisor will write the keypair file on its next cycle, but
  // policy enforcement reads the policies file directly off the temp
  // path that loadActiveAgents() prepares. We don't have that path
  // here — so we'll hand executor a pointer to a temp file we write
  // synchronously.
  const policyPath = await writeTempPolicy(agent.sns, agent.policiesYaml);

  const action = pickWarmupAction(agent.policiesYaml);
  if (!action) {
    console.warn(
      `[warmup] ${agent.sns} has no wired lending/LST protocol allowlisted, skipping`,
    );
    await markWarmupDone(agent.sns).catch(() => {});
    return;
  }

  // Make sure the agent has surfpool USDC/SOL to spend. The supervisor
  // also seeds this per-tick, but we may run before the next supervisor
  // cycle. Cheap when balance ≥ floor (single getBalance + early return).
  const seedUsdcUi =
    agent.seedAmountBusd != null
      ? Number(agent.seedAmountBusd) / 1_000_000
      : 50;
  await ensureSurfpoolUsdc(ctx.surfpool, kp.publicKey, seedUsdcUi).catch(
    (e) => console.warn(`[warmup] ensureSurfpoolUsdc: ${(e as Error).message}`),
  );

  const surfpoolAvailable = await isSurfpoolReachable(ctx.surfpool);

  try {
    const result = await executeAction({
      action,
      agentName: agent.sns,
      agentSns: agent.sns,
      walletName: agent.sns,
      kp,
      surfpool: ctx.surfpool,
      surfpoolAvailable,
      devnet: ctx.devnet,
      policyPath,
    });
    console.log(
      `[warmup] ${agent.sns} OK: ${action.type}/${
        "protocol" in action ? action.protocol : "?"
      } in ${Date.now() - t0}ms · sig=${result.txSig?.slice(0, 12) ?? "?"}…`,
    );
  } catch (err) {
    console.error(
      `[warmup] ${agent.sns} executeAction failed: ${(err as Error).message}`,
    );
  } finally {
    await markWarmupDone(agent.sns).catch(() => {});
  }
}

async function markWarmupDone(sns: string): Promise<void> {
  await dbQuery(
    `UPDATE agents SET warmup_done_at = NOW() WHERE sns = $1`,
    [sns],
  );
}

async function writeTempPolicy(sns: string, yaml: string): Promise<string> {
  const { mkdirSync, writeFileSync } = await import("node:fs");
  const { tmpdir } = await import("node:os");
  const dir = join(tmpdir(), "bundie-warmup", sns);
  mkdirSync(dir, { recursive: true });
  const p = join(dir, "policies.yaml");
  writeFileSync(p, yaml);
  return p;
}

/**
 * Long-running warmup loop. Polls every `intervalMs` (default 1000)
 * for agents needing a fast first-tick. Crash-safe: a single iteration
 * error logs and continues; the loop never exits.
 */
export async function warmupLoop(
  ctx: WarmupContext,
  shouldStop: () => boolean,
  intervalMs = 1000,
): Promise<void> {
  while (!shouldStop()) {
    try {
      const pending = await loadPendingWarmups();
      if (pending.length > 0) {
        // Run sequentially — each warmup is a single small surfpool tx,
        // and we don't want to thrash USDC/SOL seeding for many agents
        // at once. Sequential is < 2s/agent; even 10 backed-up requests
        // clears in < 20s.
        for (const a of pending) {
          await runWarmupForAgent(a, ctx);
        }
      }
    } catch (err) {
      console.error("[warmup] loop iteration failed:", (err as Error).message);
    }
    await new Promise((r) => setTimeout(r, intervalMs));
  }
  console.log("[warmup] loop stopped");
}
